### ISSUE TITLE
test

### ISSUE THREAD

**Issue by piroor** [clear-code/fluent-plugin-github-activities#1]
test

**Comment by piroor** [comment]
test

**Comment by Rikk** [comment]
@piroor please don't abandon MTH, it is a fabulous addon!
https://github.com/piroor/multipletab/issues/88
https://github.com/piroor/multipletab/pull/89
https://github.com/piroor/multipletab/pull/90

**Comment by piroor** [comment]
This is not a place to discuss about Firefox addons...
